cns/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Protool Automation & controls SCADA'
admin.site.site_url = '/'
admin.site.site_title = 'PAC SCADA Settings'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('', Homepage, name="homepage"),
    path('reports/', Reports, name="reports"),
    path('report-mail/', ReportsMail, name="report-mail"),
    path('get-status/', getStatus, name="get-status")
]

users/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator
# Create your models here.

status = [
	(0, 'Fail'),
	(1, 'Pass'),
	(2, 'Bypass'),
]

Final_status = [
	(0, 'Rejected'),
	(1, 'OK'),
]


class Data(models.Model):
	dt = models.DateTimeField(auto_now_add=True, auto_now=False)
	rating = models.CharField(max_length=255)
	hold = models.IntegerField(default=2, choices=status)
	hold_a = models.FloatField(default=0)
	hold_t = models.FloatField(default=0)
	hold_v = models.FloatField()
	trip = models.IntegerField(default=2, choices=status)
	trip_a = models.FloatField(default=0)
	trip_t = models.FloatField(default=0)
	trip_v = models.FloatField()
	arc = models.IntegerField(default=0, choices=status)
	cont = models.IntegerField(default=2, choices=status)
	knr = models.IntegerField(default=2, choices=status)
	hv = models.IntegerField(default=2, choices=status)
	status = models.IntegerField(default=0, choices=Final_status)


	def __str__(self):
		return '{} {}'.format(self.dt.strftime("%d/%m/%y %I:%M:%S %p"), self.status)

class Email(models.Model):
	email_id = models.EmailField()

	def __str__(self):
		return self.email_id


Machine_Choice = [
    (1, 'In'),
    (2, 'Out'),
]

class Machine(models.Model):
	line = models.PositiveIntegerField(verbose_name='Line Number')
	machine = models.PositiveIntegerField(verbose_name='Machne Number', choices=Machine_Choice)

	def __str__(self):
		return 'Line {} & Machine {}'.format(self.line, self.get_machine_display())


class MailStatus(models.Model):
	dt = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.dt.strftime("%d/%m/%Y")


class ShiftTime(models.Model):
	From = models.PositiveIntegerField(validators=[MaxValueValidator(23)])
	to = models.PositiveIntegerField(validators=[MaxValueValidator(23)])

	def __str__(self):
		return 'from {} to {}'.format(self.From, self.to)

users/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.generic.list import ListView
from django.utils import timezone
from datetime import datetime
from django.core import serializers
from django.db.models import Count
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from users.models import *
from users.funcs import *

import json

def Homepage(request):
	dt = timezone.localtime()
	context = DataReport(dt)
	return render(request, "index.html", context)

def Reports(request):
	context = {}
	if request.method == 'POST':
		tm = request.POST.get("time")
		etm = request.POST.get("etime")
		edt = request.POST.get("edate")
		if tm: 
			dt = datetime.strptime(request.POST.get("date")+" "+tm, "%Y-%m-%d %H:%M")
		else:
			dt = datetime.strptime(request.POST.get("date"), "%Y-%m-%d")
		if etm and edt: 
			edt = datetime.strptime(edt+" "+etm, "%Y-%m-%d %H:%M")
		elif edt:
			edt = datetime.strptime(edt, "%Y-%m-%d")
		elif etm:
			edt = datetime.strptime(request.POST.get("date")+" "+etm, "%Y-%m-%d %H:%M")
		data = RatingReport(dt, edt)
		return render(request, "reports.html", data)
	context["form"] = True
	return render(request, "reports.html", context)


def Summary(request):
	dt = timezone.localtime()
	if dt.hour < 8:
		dt = dt-timedelta(days=1)
	context = DataReport(dt)
	context.pop("data")
	return JsonResponse(context)


def getStatus(request):
	dt = timezone.localtime()
	st = ShiftTime.objects.filter().first()
	if dt.hour < 8:
		dt = dt-timedelta(days=1)
	dt = dt.replace(hour=st.From, minute=0, second=0)
	data = QueryDate(dt).order_by("-dt")
	d = data[:len(data)%20]
	if len(data)%20 == 0 and len(data) >= 20:
		d = data[:20]
	last_data = json.loads(serializers.serialize("json", d))
	summary = DataReport(dt)
	if summary.get("data"):
		summary.pop("data")
	return JsonResponse({"data": [i['fields'] for i in last_data], "tcount": len(data)-len(d)+1, "summary": summary})

def ReportsMail(request):
	context = {}
	context["form"] = True
	if request.method == 'POST':
		tm = request.POST.get("time")
		etm = request.POST.get("etime")
		edt = request.POST.get("edate")
		if tm: 
			dt = datetime.strptime(request.POST.get("date")+" "+tm, "%Y-%m-%d %H:%M")
		else:
			dt = datetime.strptime(request.POST.get("date"), "%Y-%m-%d")
		if etm and edt: 
			edt = datetime.strptime(edt+" "+etm, "%Y-%m-%d %H:%M")
		elif edt:
			edt = datetime.strptime(edt, "%Y-%m-%d")
		elif etm:
			edt = datetime.strptime(request.POST.get("date")+" "+etm, "%Y-%m-%d %H:%M")
		report = RatingReport(dt, edt)
		emails = [e.email_id for e in Email.objects.all()]
		if report and emails:
			report["dt"] = dt
			report["edt"] = edt
			msg_html = render_to_string('email.html', report)
			plain_message = strip_tags(msg_html)
			try:
				send_mail('Daily Production Report', plain_message,'cnsharidwar@gmail.com', emails,
				fail_silently=False,
				html_message=msg_html)
				context["form"] = False
			except Exception as e:
				context["errors"] = "Mail Not Sent, Please Check Internet Error"
				context["form"] = True	
		else:
			context["errors"] = "There is not Data on this Date {}".format(dt.date())
			context["form"] = True
	return render(request, "reportmail.html", context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>PAC SCADA</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block css %}{% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

{% include 'navbar.html' %}
<style>
  tr {
   line-height: 15px;
   min-height: 15px;
   height: 15px;
}
</style>
<br/>
<div class="container-fluid">
  <table class="table table-hover table-sm table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Date & Time</th>
      <th scope="col">Count</th>
      <th scope="col">Rating</th>
      <th scope="col">Hold V</th>
      <th scope="col">Trip V</th>
      <th scope="col">ARC</th>
      <th scope="col">Cont</th>
      <th scope="col">Hold</th>
      <th scope="col">Hold A</th>
      <th scope="col">Hold T</th>
      <th scope="col">Trip</th>
      <th scope="col">Trip A</th>
      <th scope="col">Trip T</th>
      <th scope="col">KNR</th>
      <th scope="col">HV</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody id="production">
    <tr>
      <th scope="row">1</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
  </table>
</div>

<script type="text/javascript">
  function getStatus(a){
    if (a==0){
      return 'Fail'
    }else if(a == 1){
      return 'Pass'
    }else if(a == 2){
      return 'Bypass'
    }
  }
  function getStatusFinal(a){
    if (a==0){
      return 'Rejected'
    }else if(a == 1){
      return 'OK'
    }
  }
</script>


<script type="text/javascript">
  // count = 1
  // var time = 1;

  // var table = document.getElementById("production");

  // var interval = setInterval(function() { 
  //     console.log(table.rows[time]+time);
  //     var d = new Date();
  //     $.ajax({
  //       type: "POST",  
  //       url: "",
  //       data: {
  //         "msg": "request",
  //         csrfmiddlewaretoken: '{{ csrf_token }}'
  //       }, 
  //       success: function(){  
  //           $("form#updatejob").hide(function(){$("div.success").fadeIn();});  
  //       },
  //       error: function(XMLHttpRequest, textStatus, errorThrown) { 
  //           console.log("Status: " + textStatus); console.log("Error: " + errorThrown); 
  //       }       
  //     });
  //     if(time>10){
  //       time=1;
  //       $(table.rows[10]).removeClass("highlight");
  //     }
  //     $(table.rows[time]).addClass("highlight");
  //     table.rows[time].cells[0].innerHTML = [d.getMonth()+1,
  //              d.getDate(),
  //              d.getFullYear()].join('/')+' '+
  //             [d.getHours(),
  //              d.getMinutes(),
  //              d.getSeconds()].join(':');
  //     table.rows[time].cells[1].innerHTML = count;
  //     if(time>1){$(table.rows[time-1]).removeClass("highlight");}
  //     time++;count++;
  // }, 2000);
</script>

<style type="text/css">
  .highlight{
    background: #33ccff;
  }
</style>

<div class="container-fluid">
  <h3 class="text-center">Summary</h3>
  <table class="table table-hover table-sm table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Date & Time</th>
      <th scope="col">Count</th>
      <th scope="col">ARC Fail</th>
      <th scope="col">Cont Fail</th>
      <th scope="col">Hold Fail</th>
      <th scope="col">Trip Fail</th>
      <th scope="col">KNR Fail</th>
      <th scope="col">HV Fail</th>
      <th scope="col">Total Fail</th>
      <th scope="col">Total Pass</th>
      <th scope="col">% Rejection</th>
    </tr>
  </thead>
  <tbody id="summary-table">
    <tr>
      <th scope="row" id="today"></th>
      <td>{{ tcount }}</td>
      <td>{{ f_arc }}</td>
      <td>{{ f_cont }}</td>
      <td>{{ f_hold }}</td>
      <td>{{ f_trip }}</td>
      <td>{{ f_knr }}</td>
      <td>{{ f_hv }}</td>
      <td>{{ rej }}</td>
      <td>{{ passed }}</td>
      <td>{{ rej_rate }}</td>
    </tr>
  </tbody>
</table>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    setInterval(function() {
      $.ajax({
        type: "POST",  
        url: "{% url 'users:get-status' %}",
        data: {
          "msg": "request",
          csrfmiddlewaretoken: '{{ csrf_token }}'
        }, 
        success: function(data){  
            $("form#updatejob").hide(function(){$("div.success").fadeIn();});
            var table = document.getElementById("production").rows;
            // for(var i = 1; i<=10; i++){
            //   console.log("row "+i, table[i])
            // }
            console.log(data);
            var table1 = document.getElementById("summary-table").rows;
            table1[0].cells[1].innerHTML = data["summary"]["tcount"];
            table1[0].cells[2].innerHTML = data["summary"]["f_arc"];
            table1[0].cells[3].innerHTML = data["summary"]["f_cont"];
            table1[0].cells[4].innerHTML = data["summary"]["f_hold"];
            table1[0].cells[5].innerHTML = data["summary"]["f_trip"];
            table1[0].cells[6].innerHTML = data["summary"]["f_knr"];
            table1[0].cells[7].innerHTML = data["summary"]["f_hv"];
            table1[0].cells[8].innerHTML = data["summary"]["rej"];
            table1[0].cells[9].innerHTML = data["summary"]["passed"];
            table1[0].cells[10].innerHTML = data["summary"]["rej_rate"];
            for (i in data['data'].reverse()){
              $(table[19]).removeClass("highlight");
              var d = new Date(data['data'][i]['dt']);
              table[i].cells[0].innerHTML = d.toLocaleString("en-US");
              table[i].cells[1].innerHTML = data["tcount"]+parseInt(i);
              table[i].cells[2].innerHTML = data['data'][i]["rating"];
              table[i].cells[3].innerHTML = data['data'][i]["hold_v"];
              table[i].cells[4].innerHTML = data['data'][i]["trip_v"];
              table[i].cells[5].innerHTML = getStatus(data['data'][i]["arc"]);
              table[i].cells[6].innerHTML = getStatus(data['data'][i]["cont"]);
              table[i].cells[7].innerHTML = getStatus(data['data'][i]["hold"]);
              table[i].cells[8].innerHTML = data['data'][i]["hold_a"];
              table[i].cells[9].innerHTML = data['data'][i]["hold_t"];
              table[i].cells[10].innerHTML = getStatus(data['data'][i]["trip"]);
              table[i].cells[11].innerHTML = data['data'][i]["trip_a"];
              table[i].cells[12].innerHTML = data['data'][i]["trip_t"];
              table[i].cells[13].innerHTML = getStatus(data['data'][i]["knr"]);
              table[i].cells[14].innerHTML = getStatus(data['data'][i]["hv"]);
              table[i].cells[15].innerHTML = getStatusFinal(data['data'][i]["status"]);
              console.log(i)
              $(table[i]).addClass("highlight");
              $(table[i-1]).removeClass("highlight");
              // if (data["count"])
            }
        },
        error: function(XMLHttpRequest, textStatus, errorThrown) { 
            console.log("Status: " + textStatus); console.log("Error: " + errorThrown); 
        }       
      });
    }, 1000);
  });
</script>
<script type="text/javascript">
  var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
  var d = new Date();
  document.getElementById("today").innerHTML = d.toLocaleDateString("hi-IN");
</script>
<div class="text-center">
  <a href="{% url 'users:reports' %}"><button type="button" class="btn btn-primary btn-sm active">Reports</button></a>
  <a href="{% url 'users:homepage' %}"><button type="button" disabled="" class="btn btn-primary btn-sm">Receive Data</button></a>
  <a href="{% url 'users:report-mail' %}"><button type="button" class="btn btn-primary btn-sm">Report Mail</button></a>
  <a href="/admin"><button type="button" class="btn btn-primary btn-sm">Settings</button></a>
</div>
<br/>
{% if errors %}
  <div class="alert alert-danger" role="alert">
    {{ errors }}
  </div>
{% endif %}
{% endblock %}

templates/reports.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}

<br/>

{% if form %}
    <main class="login-form">
        <div class="cotainer">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Production Report</div>
                            <div class="card-body">
                                <form action="" method="post">
                                	{% csrf_token %}
                                    <div class="form-group row">
                                        <label for="email_address" class="col-md-4 col-form-label text-md-right">Select Date</label>
                                        <div class="col-md-6">
                                            <input type="date" id="email_address" class="form-control" name="date" required autofocus>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="email_address" class="col-md-4 col-form-label text-md-right">Start Time</label>
                                        <div class="col-md-6">
                                            <input type="time" id="email_address" class="form-control" name="time" autofocus>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                      <label for="email_address" class="col-md-4 col-form-label text-md-right">End Date</label>
                                      <div class="col-md-6">
                                          <input type="date" id="email_address" class="form-control" name="edate" autofocus>
                                      </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="email_address" class="col-md-4 col-form-label text-md-right">End Time</label>
                                        <div class="col-md-6">
                                            <input type="time" id="email_address" class="form-control" name="etime" autofocus>
                                        </div>
                                    </div>

                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            Submit
                                        </button>
                                    </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% else %}
    <div class="container-fluid">
      <table class="table table-hover table-sm table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Rating</th>
            <th scope="col">Count</th>
            <th scope="col">ARC Fail</th>
            <th scope="col">Cont Fail</th>
            <th scope="col">Hold Fail</th>
            <th scope="col">Trip Fail</th>
            <th scope="col">KNR Fail</th>
            <th scope="col">HV Fail</th>
            <th scope="col">Total Fail</th>
            <th scope="col">Total Pass</th>
            <th scope="col">% Rejection</th>
          </tr>
        </thead>
        <tbody>
        {% for r in report %}
          <tr>
            <td>{{ r.rating }}</td>
            <td>{{ r.rating__count }}</td>
            <td>{{ r.report.f_arc }}</td>
            <td>{{ r.report.f_cont }}</td>
            <td>{{ r.report.f_hold }}</td>
            <td>{{ r.report.f_trip }}</td>
            <td>{{ r.report.f_knr }}</td>
            <td>{{ r.report.f_hv }}</td>
            <td>{{ r.report.rej }}</td>
            <td>{{ r.report.passed }}</td>
            <td>{{ r.report.rej_rate }}</td>
          </tr>
        {% endfor %}
        {% if total %}
            <tr>
                <td>All</td>
                <td>{{ total.tcount }}</td>
                <td>{{ total.f_arc }}</td>
                <td>{{ total.f_cont }}</td>
                <td>{{ total.f_hold }}</td>
                <td>{{ total.f_trip }}</td>
                <td>{{ total.f_knr }}</td>
                <td>{{ total.f_hv }}</td>
                <td>{{ total.rej }}</td>
                <td>{{ total.passed }}</td>
                <td>{{ total.rej_rate }}</td>
              </tr>
        {% endif %}
        </tbody>
      </table>
    </div>
    <script type="text/javascript">
      var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
      var d = new Date();
      document.getElementById("today").innerHTML = d.toLocaleDateString("hi-IN");
    </script>
    <div class="container-fluid">
      <table class="table table-hover table-sm table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">date & time</th>
            <th scope="col">Count</th>
            <th scope="col">Rating</th>
            <th scope="col">HOlD V</th>
            <th scope="col">TRIP V</th>
            <th scope="col">ARC</th>
            <th scope="col">CONT</th>
            <th scope="col">HOLD</th>
            <th scope="col">HOLD A</th>
            <th scope="col">HOLD T</th>
            <th scope="col">TRIP</th>
            <th scope="col">TRIP A</th>
            <th scope="col">TRIP T</th>
            <th scope="col">KNR</th>
            <th scope="col">HV</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for d in data %}
              <tr>
                <th scope="row">{{ d.dt|date:"d/m/y H:i:s" }}</th>
                <td>{{ forloop.counter }}</td>
                <td>{{ d.rating }}</td>
                <td>{{ d.hold_v }}</td>
                <td>{{ d.trip_v }}</td>
                <td>{{ d.get_arc_display }}</td>
                <td>{{ d.get_cont_display }}</td>
                <td>{{ d.get_hold_display }}</td>
                <td>{{ d.hold_a }}</td>
                <td>{{ d.hold_t }}</td>
                <td>{{ d.get_trip_display }}</td>
                <td>{{ d.trip_a }}</td>
                <td>{{ d.trip_t }}</td>
                <td>{{ d.get_knr_display }}</td>
                <td>{{ d.get_knr_display }}</td>
                <td>{{ d.get_status_display }}</td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endif %}
<br>
<div class="text-center">
  <a href="{% url 'users:reports' %}"><button type="button" disabled="" class="btn btn-primary btn-sm active">Reports</button></a>
  <a href="{% url 'users:homepage' %}"><button type="button" class="btn btn-primary btn-sm">Receive Data</button></a>
  <a href="{% url 'users:report-mail' %}"><button type="button" class="btn btn-primary btn-sm">Report Mail</button></a>
</div>
{% endblock %}